<a href="https://colab.research.google.com/github/BurhanAli232/Python_Afwera/blob/main/Lecture_5_Oprator_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Oprator practice in python
- These are some some types of oprator:

# Arithmetic operators


- Purpose: To perform mathematical calculations â€” essential for any data-driven logic, automation, or financial app.
- For More info:https://www.geeksforgeeks.org/python-arithmetic-operators/
![image_2025-05-02_225008793.png]()

#### Addition oprator

In [ ]:
x,y=4,5 #assign the value(4,5) in variable(x,y)
# first we preform the addition function so let's start
print("Addition of two number",x+y)
# now i want to take the input from user and addition both number
a=int(input("Please enter first number for addition: "))
b=int(input("Please enter second number for addition: "))
print("aAddition of two number:",a+b)

Addition of two number 9
Please enter first number for addition: 4
Please enter second number for addition: 9
aAddition of two number: 13

In [ ]:
# if we take input like this
a=input(print("Enter any digit: ")) # it display the None
# the reason of none is print return None and we are passing None therefore None display

Enter any digit:
None9

#### Subtraction Oprator

In [ ]:
# we use the variable of addition oprator
print("The subtraction of two number: ",x-y)

The subtraction of two number:  -1

In [ ]:
# Now i take the input from user and display the subtraction output
a,b=map(int,input("Please enter two number for subtraction with space like 4 5: ").split()) # to take two input in one
print("The subtraction of two number: ",a-b)
# explanation two take more than one input from one line
# 1-Input function use to take the full line of input
# 2-split() function is use to split it into list of string like ["4","5"]
# 3-map(int,  ) function is use to conver each string into an integer
# 4-a,b use unpack the two value(4,5) int a and b

Please enter two number for subtraction with space like 4 5:9 5
The subtraction of two number:  4

#### Multiplication

In [ ]:
# we use the use the value from addition oprator
print("The multiplication of two number:",a*b)

The multiplication of two number: 45

In [ ]:
# now take input from user
a,b=map(int,input("Please enter two number for multiplication with spaace").split()) # to take value from user also explain in above cell full details
print("The result of multiplication: ",a*b) # print the output

Please enter two number for multiplication with spaace5 6
The result of multiplication:  30

#### Division

In [ ]:
# simple i divide two number
print("The division of two number:",a/b)
# from user input
a,b=map(int,input("Enter two number for division with space use").split())
print("The division of two number:",a/b)

The division of two number: 0.8333333333333334
Enter two number for division with space use9 3
The division of two number: 3.0

#### Floor Division

In [ ]:
# the floor division are use to print output without float value
print("The floor division of two number: ",x//y)
# Now i take input from user
a,b=map(int,input("Please enter two digit for floor division with space").split())
print("The floor division of two number: ",a//b)

The floor division of two number:  0
Please enter two digit for floor division with space9 3
The floor division of two number:  3

#### Modulus (remainder)

In [ ]:
# the modulus just like a division but a bit difference the modulus return the reminder as an output
print("The modulus of two number: ",x%y)
# take the input from user'
a,b,c=map(int,input("Please enter the three digit with space:").split()) # take 3 input from user
print("The modulus of  first two number:",a%b) # find modulus a,b
print("The modulus of last two number: ",b%c) # find modulus b,c

The modulus of two number:  4
Please enter the three digit with space:27 12 5
The modulus of  first two number: 3
The modulus of last two number:  2

#### Exponentiation

In [ ]:
# the exponentioal oprator are use to assign the
print("The exponent of two number: ",x**y)
# now take the input from user
a,b,c=map(int,input("Please enter three number for exponent opration:").split())
print(a**b**c) # i find the 5^4=625 so i enter 5 2 2 and the ans is 625

The exponent of two number:  1024
Please enter three number for exponent opration:5 2 2
625

# Some example to more explation(Arithmetic oprator)

## 1-Calculate the area of a rectangle (length Ã— width)

In [ ]:
#i take the input frpm user and print the area of a rectangle
lenght=int(input("Please enter the Lenght: "))
width=int(input("Please enter the width: "))
print("The are of a rectangle is: ",lenght*width)

Please enter the Lenght: 3
Please enter the width: 4
The are of a rectangle is:  12

## 2-Convert temprature from celsius to fahrenheit

In [ ]:
# The formula is F=(C*9/5)=32
C=25
F=(C*9/5)+32
print("The temprature in fahrenheit is: ",F)

The temprature in fahrenheit is:  77.0

## 3-Find the cube of the number using exponentiation oprator

In [ ]:
# i find the cube of 5^3=125
print("The cube of 5 is: ",5**3)

The cube of 5 is:  125

## 4-Calculate the average of 3 test scores

In [ ]:
# in this problem take 3 number from user and find the average
a,b,c=map(int,input("Please enter three number with space for finding the average ").split())
print("The average of three number is: ",(a+b+c)/3)

Please enter three number with space for finding the average 3 6 9
The average of three number is:  6.0

## 5-Give total seconds, convert it to minutes and second

In [ ]:
# in this example take the input from user as a second
tottal_second=int(input("Please enter the second "))
minutes=tottal_second//60
second=tottal_second%60
print(f"Your time is {minutes} Minutes and {second} seconds")

Please enter the second 125
Your time is 2 Minutes and 5 seconds

## 6-Calculate the final bill after adding 15% tip to a meal cost

In [ ]:
# this problem explain print the final bill after ading 15% tip
final_bill=int(input("Please enter you total bill without tax | tip "))
print("You bill without tip ",final_bill)
print("Your bill after tip",final_bill+(final_bill*0.15)) # formula for adding the tax on tottal bill

Please enter you total bill without tax | tip 200
You bill without tip  200
Your bill after tip 230.0

## 7-Compute Simple intrest

In [ ]:
# Simple in this example we find the intrest
# formula to find intrest=(P*R*T)/100,p=Principle,R=rate,T=time
P,R,T=200,2,4
print("The intrest is: " ,(P*R*T)/100)

The intrest is:  16.0

- Please drink one glass water Also belive we can do
- Just we need focus,Consistent,hard work and attention to details
- So please take a 5-10 minutes break your health is too imporatant than coding beacuse you'r parents take too much expectation when we are born so focus on self also parents after that coding
- Thank You for take break

# Assignment Operators

- This oprator are use to assign the value
- for more details click here :https://www.geeksforgeeks.org/assignment-operators-in-python/

#### Assignment

In [ ]:
# the asssignment oprator are use to assign the value in variable
x=5 # assign the value 5 in variable x
y=10 # assign the value 10 in variable y
print(x)
print(y)

5
10

#### Addition Assignment

In [ ]:
# the addition assignment oprator are use add ans assign the value into variable
x+=y # this line add the privious value into x also assign
x1=5+y # the line are also same functioon assign and addition
print(x,x1)

15 15

#### Subtraction Assignment

In [ ]:
# this oprator is use to subtract and assign the value this oprator is similar toaddition but these both oprator work vice virsa
x-=y # x=15,y=10
print(x)

5

#### Multiplication Assignment

In [ ]:
#  the function is use to assign and multiply the 2 number its just like Multiplication Arithmetic but here just one addition to assign value
x*=y # x=x*y
print(x)

50

#### Division Assignment

In [ ]:
# these are similar to other assignment oprator
x/=y # x=x/y
print(x)

5.0

#### Floor Division Assignment

In [ ]:
# floor is just like division but just one difference this oprator provide the output without float vaue
x,y=10,5
x//=y # x=x//y
print(x)

2

#### Modulus Assignment

In [ ]:
# here is the another example of modulus oprator
x,y=10,5
x%=y # x=x%y
print(x)

0

#### Exponentiation Assignment

In [ ]:
# this oprator are mostly use to take the power of any number
x,y=10,3
x**=y #x=x**y
print(x)

1000

- The all assignment oprator are poosible preform to take input from user So i'll preformed in next few example

#### Please drink a one glass water and trust on you we can do python

# Some example to more explanation (Assignment oprator)

## 1-Start with x = 10, then increase it by 5 using +=

In [ ]:
x=int(input("Plesase enter '10' "))
print("The value of x before adding ",x)
x+=5
print("The value of x after adding ",x)

Plesase enter '10' 10
The value of x before adding  10
The value of x after adding  15

## 2-A counter starts at 0. Simulate a game where score increases by 10, then drops by 3

In [ ]:
x=0
while(x!=10):
  print("The Value of x is: ",x)
  x+=1
x-=3
print("The value of x after subtract: ",x )

The Value of x is:  0
The Value of x is:  1
The Value of x is:  2
The Value of x is:  3
The Value of x is:  4
The Value of x is:  5
The Value of x is:  6
The Value of x is:  7
The Value of x is:  8
The Value of x is:  9
The value of x after subtract:  7

## 3-A value is squared three times using **=

In [ ]:
x=2
print("The value of x is ",x)
x**=2
print("The value of x after first square: ",x)
x**=2
print("The value of x after second square: ",x)
x**=2
print("The value of x after third square: ",x)

The value of x is  2
The value of x after first square:  4
The value of x after second square:  16
The value of x after third square:  256

## 4-Reduce a salary of 10000 by 10% using assignment.

In [ ]:
salary=10000
salary-=salary*0.10
print("The reduced salary ",salary)

The reduced salary  9000.0

## 5-Start with a number and keep halving it until itâ€™s less than 1.

In [ ]:
num=int(input("Please enter number under 30 "))
while(num>1):
  print("The value of num is: ",num)
  num/=2
print("Your answer is ",num)

Please enter number under 30 29
The value of num is:  29
The value of num is:  14.5
The value of num is:  7.25
The value of num is:  3.625
The value of num is:  1.8125
Your answer is  0.90625

## 6-Track a bank account balance with multiple deposit and withdrawal operations

In [ ]:
# i take the input from user
balance=1000
deposit_amount=int(input("Please enter your first deposit amount "))
deposit_amount2=int(input("Please enter your second deposit amount "))
deposit_amount3=int(input("Please enter your third deposite amount "))
withdraw_amount=int(input("Please enter your first withdraw amount "))
withdraw_amount2=int(input("Please enter your second withdraw amount "))
balance+=deposit_amount
balance+=deposit_amount2
balance+=deposit_amount3
balance-=withdraw_amount
balance-=withdraw_amount2
print("Your tottal balance is ",balance)

Please enter your first deposit amount 10
Please enter your second deposit amount 10
Please enter your third deposite amount 10
Please enter your first withdraw amount 10
Please enter your second withdraw amount 10
Your tottal balance is  1010

- Sure you are right thinking this problem can resolved other and easy way but i try to resolve every problem with different pattern
- Practice makes men perfect so practice and practice
- Trust on yourself and motivate your self

# Comparison Operators

- Now let's start after drink water and take a 5 mint break
- For more info:https://www.w3schools.com/python/gloss_python_comparison_operators.asp

#### Equal to

In [ ]:
# i try to preform some real life example so let's start
age=int(input("Please enter your age: "))
if age==18:
  print("Now you are eligible to get your National ID")
elif age<18:
  print("You not eligible now ")

Please enter your age: 18
Now you are eligible to get your National ID

#### Not Equal to

In [ ]:
age=int(input("Please enter your age: "))
if age!=40:
  print("You are eligible for PHD if you are under 40")

Please enter your age: 21
You are eligible for PHD if you are under 40

#### Greater than

In [ ]:
age=int(input("Please enter your age: "))
if age>18:
  print("You are eligible to apply national ID")
elif age==18:
  print("You are eligible to apply national ID")
else:
  print("You are not eligible to apply national ID")

Please enter your age: 21
You are eligible to apply national ID

#### Greater than or equal

In [ ]:
age=int(input("Please enter your age: "))
if age>=18:
  print("You are eligible to apply national ID")
else:
  print("You are not eligible")

Please enter your age: 21
You are eligible to apply national ID

#### Less than

In [ ]:
age=int(input("Please enter your age: "))
if age<18:
  print("You are not eligible to apply ID")
else:
  print(" You are eligible for ID apply")

Please enter your age: 21
 You are eligible for ID apply

#### Less than or equal

In [ ]:
age=int(input("Please enter your age: "))
if age<=17:
  print("You are a under age to get you ID")
else:
  print("You are eligible for apply")

# Some example to more explain (Comparison oprator)

## 1-Check if two numbers are equal

In [ ]:
# now we check two number equal or not and print the output
num,num1=map(int,input("Please enter two number with space " ).split())
if num==num1:
  print("Both number are equal ")
else:
  print("Both number are not equal")

Please enter two number with space 2 2
Both number are equal

## 2-Determine if a person is a teenager (age between 13 and 19)

In [ ]:
# now i take age from user and we use and oprator
age=int(input("Please enter your age: "))
if age<=19 and age>=13:
  print("You are now in teenage ")
else:
  print("You are not in teenage")

Please enter your age: 19
You are now in teenage

## 3-Verify if a password length is valid (between 8 and 16 characters)

In [ ]:
passward=str(input("Please enter your passward "))
if len(passward)>=8 and len(passward)<=16:
  print("Your passward is volid ")
else:
  print("Your passward less or grather please try different ")

Please enter your passward BUrhan12
Your passward is volid

## 4-Compare student marks with passing marks and print result

In [ ]:
marks=int(input("Please enter your marks "))
if marks>=50:
  print("COngrats you are pass ")
else:
  print("YOu need to repeat the course ")

Please enter your marks 82
COngrats you are pass

- Again time to drink water so go and drink water comeback and start from here
- So quickly go and come back then start don't waste your time

# Logical Operators

- Let's start with full motivation

In [ ]:
a,b=True,False
print("And",a and b)
print(" or", a or b)
print("Not", not b)

And False
 or True
Not True

#### and

In [ ]:
# the logical oprator give the ans in true or false
# the add condition true if all the value true
username=str(input("Please enter the username "))
passward=str(input("Please enter the passward "))
if username=='admin' and passward=='12345':
  print("You are Login")
else:
  print("Your username or passward is incorrect ")

Please enter the username admin
Please enter the passward 12345
You are Login

#### or

In [ ]:
# or condition true if anyone id true
digit_passward=str(input("Please your mobile passward in digit "))
alpha_passward=str(input("Please your mobile passward in alphabetic "))
recover_id=str(input("Please enter you recover_Id to access your mobile "))
if digit_passward=='12345' or alpha_passward=='abcd' or recover_id=='0000':
  print("You can use now this mobile ")
else:
  print("your provide all details missmatch")

Please your mobile passward in digit 1298
Please your mobile passward in alphabetic abcd
Please enter you recover_Id to access your mobile 9090
You can use now this mobile

#### not

In [ ]:
# simply this oprator are used to reverse the value
a=True
print("and",a and a)
print("Not",not a) # it convert the ans into false

and True
Not False

# Some example to more explain (Logical oprator)

## 1-Check if a number is positive and even.

In [ ]:
num=int(input("Please enter the number "))
if num>0 and num%2==0:
  print("The number is positive and even ")
else:
  print("The number is negative or odd ")

Please enter the number 8
The number is positive and even

## 2-Validate login with correct username and password

In [ ]:
username=str(input("Please enter your username "))
passward=str(input("Please enter your passward "))
if username=='admin' and passward=='1234':
  print("Now you can use mobile ")
else:
  print("Please try again ")

Please enter your username admin
Please enter your passward 1234
Now you can use mobile

## 3-Check if a user is eligible for a discount (coupon or member)

In [ ]:
coupon=input("Do you have any coupon (yes/no) ") == 'yes'
member=input("Are you a member (yes/no) ") =='no'
if coupon==True or member==True:
  print("You are eligible for discount ")
else:
  print("You are not eligible for discount ")

Do you have any coupon (yes/no) yes
Are you a member (yes/no) no
You are eligible for discount

## 4-Ensure a file can be downloaded only if internet is on and battery > 20%

In [ ]:
internet=input("Do you have internet (yes/no) ")
battery=input("Please enter your battery level ")
if internet=='yes' and battery>='20':
  print("Now you can download the file ")
else:
  print("Please check your internet and battery level ")

Do you have internet (yes/no) yes
Please enter your battery level 21
Now you can download the file

## 5-Validate a voter: age >= 18 and citizen == True

In [ ]:
age=input("Please enter your age ")
citizen=input("Are you a citizen (yes/no) ")
if age>='18' and citizen=='yes':
  print("You are eligible to vote ")
else:
  print("You are not eligible for vote ")

Please enter your age 21
Are you a citizen (yes/no) yes
You are eligible to vote

## 6-Warn user if they are not wearing a seatbelt

In [ ]:
seetblet=input("DO you wear the seetblet (yes/no) ")
if not seetblet=='yes':
  print("PLease wear the seetblet ")
else:
  print("Good you are safe now")

DO you wear the seetblet (yes/no) yes
Good you are safe now

- Please drink a water also motivate  beacuse the oprator topic almost complete just we resole some more example for nore experience.

- Please rest 5-10 mint then we start some more example

# Multi-oprator problem

- let's ready to start the multi-oprator problem so please give 100% focus on here

## 1-Take product price and discount percentage, calculate final price and check if itâ€™s under 1000

In [ ]:
price=int(input("Please enter the price "))
discount=10
final_price=price-(price*discount/100)
print(final_price)
if final_price<1000:
  print("Your final price is less than 1000 ")
else:
  print("Your price is more than 1000 ")

Please enter the price 1200
1080.0
Your price is more than 1000

## 2-Input a number and check if it is positive and even

In [ ]:
num=int(input("PLease enter the number "))
if num>0 and num%2==0:
  print("The number is even | +ve")
else:
  print("The number is odd | -ve ")

PLease enter the number 4
The number is even | +ve

## 3-Input marks of 3 subjects, calculate average, and decide if student passed with distinction (avg > 75)

In [ ]:
english,computer,math=map(int,input("Please the english,computer and math number with using space ").split())
average=english+computer+math/3
if average>75:
  print("You are pass ")
else:
  print("You need to again try ")

Please the english,computer and math number with using space 40 50 60
You are pass

## 4-Take user age and citizenship status, determine if eligible to vote (age â‰¥ 18 and citizen == True

In [ ]:
age=input("Please enter your age ")
citizen=input("Are you a citizen (yes/no) ")
if int(age)>=18 and citizen=='yes':
  print("You are eligible for vote ")
else:
  print("You are under age now ")

Please enter your age 21
Are you a citizen (yes/no) yes
You are eligible for vote

## 5-Enter hours worked and rate/hour, calculate salary with 1.5x overtime if hours > 40

In [ ]:
hours=int(input("PLease yours working hours "))
rate=200
if hours>40:
  salary=(hours*rate+(hours-40)*rate*1.5)
  print("Your salary is ",salary)
else:
  print("Your salary is ",hours*rate)

PLease yours working hours 45
Your salary is  10500.0

## 6-Calculate BMI from height and weight and classify it (Normal if 18.5 â‰¤ BMI < 25)

In [ ]:
height,weight=map(int,input("Please enter the height and weight using space ").split())
bmi=weight/height**2
if 18.5<=bmi<25:
  print("Normal BMI ",bmi)
else:
  print("Not normal", bmi)

Please enter the height and weight using space 3 200
Normal BMI  22.22222222222222

## 7-Input income, check if tax should be applied (if income > 5 lakhs, apply 10% tax)

In [ ]:
income=input("Please enter the income ")
if float(income)>500000:
  tax=0
  tax=float(income)*0.10
  print("Your income after tax ",tax)
else:
  print("Your are not eligible for tax ",income)

Please enter the income 600000
Your income after tax  60000.0

## 8-Check if a number is divisible by both 3 and 5, and print a message

In [ ]:
num=int(input("Please enter the number for checking it's divisible by 3 and 5 "))
if num%3==0 and num%5==0:
  print("The number is divisiblle on 3 & 5 ")
else:
  print("The number is not divisible ")

Please enter the number for checking it's divisible by 3 and 5 15
The number is divisiblle on 3 & 5

## 9-Compare two salaries, increase the smaller one by 20%, then print both

In [ ]:
salary1,salary2=map(int,input("Please enter two salary with using space ").split())
if salary1>salary2:
  salary2+=salary2*0.2
  print("The salary after increase ",salary2)
else:
  salary1+=salary1*0.2
  print("The salary after increase ",salary1)

Please enter two salary with using space 20 40
The salary after increase  24.0

## 10-Accept username and password; check both are correct and password length â‰¥ 8

In [ ]:
username=input("Please enter the username minimum 8 digit ")
passward=input("Please enter the passward minimum 8 digit ")
if passward=='abcdefgh' and username=='Burhan0145':
  print("Now your are login ")
else:
  print("Your username or passward is incorrect ")

Please enter the username minimum 8 digit Burhan0145
Please enter the passward minimum 8 digit abcdefgh
Now your are login

## 11-Convert total seconds to minutes and seconds, and check if duration exceeds 5 minutes

In [ ]:
second=int(input("Please enter the second "))
minutes=second//60
seconds=second%60
if minutes>5:
  print("The duration is more than 5 minutes: ",minutes)
else:
  print("The duration is less than 5 minutes: ",minutes)

Please enter the second 360
The duration is more than 5 minutes:  6

## 12-Accept three angles, verify if they form a triangle, and check if it's a right triangle

In [ ]:
a,b,c=map(int,input("Please enter the 3 angle for triangle with space ").split())
if a+b+c==270:
  print("It's valid triangle ")
if a==90 and b==90 and c==90:
  print("its right triangle ")
else:
  print("It's not right triangle ")

Please enter the 3 angle for triangle with space 90 90 90
It's valid triangle
its right triangle

## 13-Take a number and raise it to power 3, then check if result is > 500

In [ ]:
num=input("please entr the number ")
if int(num)**3>500:
  print("The number is greater ",int(num)**3)
else:
  print("The number is less ",int(num)**3)

please entr the number 9
The number is greater  729

## 14-Input shopping cart value and membership status, apply 10% discount if cart > 1000 or member

In [ ]:
num1,num2,num3,num4,num5=map(int,input("Please enter the 5 items value using space ").split())
member=input("Are you a member (yes/no) ")
if (num1+num2+num3+num4+num5)>1000 or member=='yes':
  discount=(num1+num2+num3+num4+num5)*0.10
  price=(num1+num2+num3+num4+num5)-discount
  print("Your total price after discount ",price)
else:
  print("Your total price is ",num1+num2+num3+num4+num5)

Please enter the 5 items value using space 10 10 10 10 10
Are you a member (yes/no) yes
Your total price after discount  45.0

## 15-Take original price, apply tax and discount, and determine the final amount

In [ ]:
price=float(input("Please enter the price "))
price+=price*0.15
if price>1000:
  final_amount=0
  final_amount=price-(price*0.20)
  print("Your final amount is ",final_amount)
else:
  print("You final amount is ",price)

Please enter the price 1001
Your final amount is  920.9200000000001

## 16-Input a number and check if it is a multiple of 10 and not zero

In [ ]:
num=int(input("Please enter the number "))
if num%10==0 and num!=0:
  print("The give number is multiple of 10 and not zero ")
  print("Your number is ",num)
else:
  print("Your number is not multiple of 10 or zero ")
  print("Your number is ",num)

Please enter the number 100
The give number is multiple of 10 and not zero
Your number is  100

## 17-Accept a value, halve it until itâ€™s < 1, and count how many divisions occurred

In [ ]:
value=input("Please enter the value ")
count=0
print("Your enter value is: ",value)
while float(value)>=1:
  value=float(value)/2
  count+=1
  print(f"The value of count | value {count,value}")
else:
  print("Your value is less than 1 ",value)

Please enter the value 25
Your enter value is:  25
The value of count | value (1, 12.5)
The value of count | value (2, 6.25)
The value of count | value (3, 3.125)
The value of count | value (4, 1.5625)
The value of count | value (5, 0.78125)
Your value is less than 1  0.78125

## 18-Input the number of correct and wrong answers in a quiz, calculate score and pass/fail

In [ ]:
quiz=input("Please enter the total quiz(please enter 30-35): ")
wrong_quiz=input("Please enter the wrong_quiz: ")
remain_quiz=int(quiz)-int(wrong_quiz)
score=0
remain_quiz*=2
score+=remain_quiz
if score>=40:
  print("You are pass")
  print(f"You'r marks is 60 out of {score}")
else:
  print("You need to one more try ")
  print(f"You'r marks is 60 out of {score}")

Please enter the total quiz(please enter 30-35): 35
Please enter the wrong_quiz: 16
You need to one more try
You'r marks is 60 out of 38

## 19-Simulate a bank balance update: apply deposits and withdrawals, check if final balance is negative

In [ ]:
final_balance=0
print(f"You'r current balance is {final_balance} PKR")
deposit_amount1,deposit_amount2,deposit_amount3=map(int,input("Please enter 3 amount which you want to deposit: ").split())
withdraw_amount,withdraw_amount2=map(int,input("Please enter two withdraw amount using space ").split())
final_balance+=deposit_amount1+deposit_amount2+deposit_amount3
final_balance-=withdraw_amount+withdraw_amount2
if final_balance>0:
  print(f"You'r balance is {final_balance} and you'r balance is +VE ")
else:
  print(f"You'r balance is {final_balance} and you'r balance is -VE ")

You'r current balance is 0 PKR
Please enter 3 amount which you want to deposit: 50 50 50
Please enter two withdraw amount using space 100 100
You'r balance is -50 and you'r balance is -VE

## 20-Accept 2 product weights, check if their sum exceeds a limit and if either is too heavy

In [ ]:
weight1,weight2=map(int,input("Please enter two weight using space ").split())
sum=weight1+weight2
if sum>30:
  print("Your weight is more than 30KG you need to left some items ")
else:
  print("Your weight is under 30KG you can go with this bag ")

Please enter two weight using space 30 1
Your weight is more than 30KG you need to left some items